[package]
name = "bcut"
version = "1.0.3"
authors = ["Allen Wild <allenwild93@gmail.com>"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
anyhow = "1"
hexyl = { git = "https://github.com/aswild/hexyl", default-features = false }
structopt = "0.3"

[dependencies.regex]
version = "1.4"
default-features = false
features = ["std"]

[profile.release]
lto = "thin"
