[package]
name = "bcut"
version = "0.1.0"
authors = ["Allen Wild <allenwild93@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
hexyl = "0.8.0"
structopt = "0.3.15"

[dependencies.regex]
version = "1.3.9"
default-features = false
features = ["std"]

[profile.release]
lto = true
codegen-units = 1
